global_frame: map
robot_base_frame: base_link
map_topic: /map
obstacle_range: 6.0
raytrace_range: 8.5
footprint: [[0.10, 0.10], [0.10, -0.10], [-0.10, -0.10], [-0.10, 0.10]]
subscribe_to_updates: true
always_send_full_costmap: true
obstacle_layer: {observation_sources: laser_scan_sensor,origin_z: 0.0, laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}}
