global_costmap:
  update_frequency: 2.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  width: 8
  height: 8
  resolution: 0.05
  static_map: false
  rolling_window: false
  plugins:
    - {name: static_layer,           type: "mw_costmap::StaticLayer"}
    # - {name: obstacle_layer,         type: "mw_costmap::ObstacleLayer"}
    - {name: inflation_layer,        type: "mw_costmap::InflationLayer"}
  inflation_layer:
    cost_scaling_factor: 3.0
    inflation_radius: 0.4
