mw_maxl_planner:
  use_laser: true
  odomTopic: "/odom"
  plot_path: true

  pathFolder: $(find mw_maxl_planner)/paths
  autonomyMode: true
  map_frame: "map"
  robot_frame: "base_link"
  velodyne_frame: "velodyne"
  laser_frame: "laser"


  lookahead_goal_on_path: true
  min_lookahead: 1 # 0.2 #1.5
  max_lookahead: 1.5 # 3
  closest_point_index_search: 10
  max_y_deviation: 1.0
  min_radius: 0.1
  max_radius: 1.0
  max_omega_radius: 1.0
  max_path_dev: 1.0
  lookahead_point_distance: 0.1 

  # vehicle dimension for ROSbot
  vehicleLength: 0.01 # 0.23    
  vehicleWidth: 0.01 #0.2     
  
  sensorOffsetX: 0.1    # not having effect
  sensorOffsetY: 0      # not having effect

  maxSpeed: 0.6 # 0.6 # 0.4
  maxAccel: 0.5 # 1.0 #0.5

  yaw_gain: 2.5       # yaw gain used when robot is in motion
  stop_yaw_gain: 0.6  # yaw gain used when robot is stopped/almost stopped
  max_yaw_rate: 0.5   # maximum yaw rate for the robot
  
  direction_weight: 0.2 # 0.02        # weight to change in direction
  direction_threshold: 90 # 120      # in degrees

  # for obstacle inflation
  x_inflate: 0 #0.16 # +- x_inflate /2 meters in x-direction of path frame
  y_inflate: 0 #0.80 #+- y_inflate / 2 meters in y-direction of path frame

  #enable visualisation of detailed data (pointcloud data)
  vis_pointcloud: true
